[package]
name = "replace_me"
version = "0.1.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tversteeg/replace_me"
documentation = "https://docs.rs/replace_me"
description = ""
keywords = []
categories = []

[badges]
is-it-maintained-issue-resolution = { repository = "tversteeg/replace_me" }
is-it-maintained-open-issues = { repository = "tversteeg/replace_me" }

[dependencies]
anyhow = "1.0.28"
hibitset = "0.6.3"
legion = "0.2.1"
lyon = { version = "0.15.8", features = ["extra"] }
miniquad = "0.3.0-alpha.0"
usvg = { version = "0.9.0", default_features = false }
vek = "0.10.2"
